manifest:
  self:
    path: passinglink
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: passinglink
      url-base: https://github.com/passinglink
  projects:
    - name: zephyr
      remote: passinglink
      revision: pl-v2.4-20201115
      import: true
    - name: mcuboot
      remote: passinglink
      revision: pl-v2.4-20201115
      path: bootloader/mcuboot
    - name: mbedtls
      remote: passinglink
      revision: pl-v2.4-20201110
      path: modules/crypto/mbedtls
    - name: mbed_embed
      remote: passinglink
      revision: pl-v2.4-20201122
      path: tools/mbed_embed
    - name: pcb
      remote: passinglink
      revision: master
      path: pcb
